=== SalmaYousry01/XML_Labs/lab3/Employee/employee.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
 
  <xs:complexType name="employeeType"> 
    <xs:sequence> 
      <xs:element name="name" type="xs:string"/> 
      <xs:element name="phones" type="phonesType"/> 
      <xs:element name="addresses" type="adressesType"/> 
      <xs:element name="mail" type="xs:string"/> 
    </xs:sequence> 
  </xs:complexType> 
 
  <xs:complexType name="phonesType"> 
    <xs:sequence> 
      <xs:element name="phone" maxOccurs="unbounded"> 
        <xs:complexType> 
          <xs:simpleContent> 
            <xs:extension base="xs:string"> 
              <xs:attribute name="type" type="xs:string" use="required"/> 
            </xs:extension> 
          </xs:simpleContent> 
        </xs:complexType> 
      </xs:element> 
    </xs:sequence> 
  </xs:complexType> 
 
  <xs:complexType name="adressesType"> 
    <xs:sequence> 
      <xs:element name="address"> 
        <xs:complexType> 
          <xs:sequence> 
            <xs:element name="street" type="xs:string"/> 
            <xs:element name="building" type="xs:string"/> 
            <xs:element name="region" type="xs:string"/> 
            <xs:element name="city" type="xs:string"/> 
            <xs:element name="country" type="xs:string"/> 
          </xs:sequence> 
        </xs:complexType> 
      </xs:element> 
    </xs:sequence> 
  </xs:complexType> 
 
  <!-- Define root element --> 
  <xs:element name="employees"> 
    <xs:complexType> 
      <xs:sequence> 
        <xs:element name="employee" type="employeeType" maxOccurs="unbounded"/> 
      </xs:sequence> 
    </xs:complexType> 
  </xs:element> 
 
</xs:schema>

=== SalmaYousry01/XML_Labs/lab3/Employee/employee.xml
<?xml version="1.0"?> 
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee.xsd">

	<employee>
		<name>Name: Salma Yousry</name>
		<phones>
			<phone type="Home">Home:5974823</phone>
			<phone type="Work">Work:+276645372</phone>
			<phone type="moblie">Mobile:01243556734</phone>
		</phones>

		<addresses>
			<address>
				<street>street1</street>

				<building>123</building>

				<region>region1</region>

				<city>city1</city>

				<country>country1</country>
			</address>
		</addresses>

		<mail>salma@gmail.com</mail>
	</employee>

	<employee>
		<name>Name: Salma</name>

		<phones>
			<phone type="Home">Home:5974823</phone>
			<phone type="Work">Work:+276645372</phone>
			<phone type="moblie">Mobile:01243556734</phone>
		</phones>

		<addresses>
			<address>
				<street>street2</street>

				<building>456</building>

				<region>region2</region>

				<city>city2</city>

				<country>country2</country>
			</address>
		</addresses>

		<mail>salma@gmail.com</mail>
	</employee>
</employees>
